In [1]:
import numpy as np
import pandas as pd
import datetime
import matplotlib.pylab as plt

In [3]:
data=pd.read_csv('Melbourne_housing_extra_data.csv')
# data=pd.read_csv('Melbourne_housing_extra_data.csv',dayfirst=True,parse_dates=True,index_col='Date')
data.head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude
0,Abbotsford,68 Studley St,2.0,h,NaN,SS,Jellis,3/09/2016,2.5,3067.0,2,1,1,126,NaN,NaN,Yarra,-37.8014,144.9958
1,Abbotsford,85 Turner St,2.0,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,2,1,1,202,NaN,NaN,Yarra,-37.7996,144.9984
2,Abbotsford,25 Bloomburg St,2.0,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,2,1,0,156,79,1900,Yarra,-37.8079,144.9934
3,Abbotsford,18/659 Victoria St,3.0,u,NaN,VB,Rounds,4/02/2016,2.5,3067.0,3,2,1,0,NaN,NaN,Yarra,-37.8114,145.0116
4,Abbotsford,5 Charles St,3.0,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,3,2,0,134,150,1900,Yarra,-37.8093,144.9944

In [4]:
# data.Landsize.astype('int')
data.dtypes

Suburb           object
Address          object
Rooms           float64
Type             object
Price           float64
Method           object
SellerG          object
Date             object
Distance        float64
Postcode        float64
Bedroom2         object
Bathroom         object
Car              object
Landsize         object
BuildingArea     object
YearBuilt        object
CouncilArea      object
Lattitude        object
Longtitude       object
dtype: object

In [88]:
test=data.head(100)

In [3]:
def val_counts(var):
    print(data[var].value_counts())
    print(data[var].nunique())

In [4]:
val_counts('Suburb')
val_counts('Rooms')
val_counts('Type')
val_counts('Method') #can ignore
val_counts('SellerG')#can ignore
# val_counts('year')
# val_counts('month') # month 3-8 more sales
val_counts('Postcode')

Reservoir             444
Bentleigh East        314
Richmond              301
Glen Iris             266
Preston               263
Kew                   251
Brighton              248
South Yarra           242
St Kilda              235
Brunswick             228
Coburg                226
Camberwell            226
Brighton East         226
Balwyn North          224
Essendon              222
Hawthorn              216
Glenroy               213
Malvern East          212
Northcote             210
Port Melbourne        204
Pascoe Vale           193
Prahran               187
Balwyn                180
Yarraville            175
Bentleigh             170
Thornbury             164
Toorak                164
Carnegie              161
Hawthorn East         161
Hampton               157
                     ...
Albion                 33
Spotswood              31
Essendon West          30
South Kingsville       29
East Melbourne         29
Ivanhoe East           29
Cremorne               28
Gowanbrae              27
Balaclava              26
Kealba                 25
Brooklyn               24
Jacana                 24
Williamstown North     23
    RE                 20
Essendon North         20
Keilor Park            20
Bellfield              19
Kingsbury              16
Caulfield              14
Caulfield East         12
Travancore             11
Kooyong                11
Docklands              10
Campbellfield          10
Ripponlea              10
Strathmore Heights      9
Seaholme                8
Gardenvale              7
Princes Hill            6
Burnley                 5
Name: Suburb, dtype: int64
143
3.0     5800
2.0     4197
4.0     2707
1.0      801
5.0      629
6.0       60
8.0       11
7.0       10
10.0       3
12.0       2
9.0        2
Name: Rooms, dtype: int64
11
h    9080
u    3568
t    1574
Name: Type, dtype: int64
3
S     8406
SP    2013
PI    1883
VB    1098
SN     587
PN     121
W       51
SA      51
SS      12
Name: Method, dtype: int64
9
Nelson                  1657
Jellis                  1553
hockingstuart           1284
Marshall                1038
Barry                    990
Buxton                   758
Ray                      534
Biggin                   449
Brad                     361
Woodards                 324
Fletchers                317
RT                       297
Miles                    260
Greg                     257
Jas                      232
Sweeney                  218
Gary                     213
Kay                      206
McGrath                  181
Noel                     169
Hodges                   144
Village                  143
Stockdale                135
Williams                 126
Love                      97
Douglas                   93
Raine                     90
Chisholm                  88
Rendina                   79
Harcourts                 68
                        ...
Naison                     1
Geoff                      1
Propertyau                 1
Meadows                    1
Foxtons                    1
@Realty                    1
AIME                       1
Xynergy                    1
Icon                       1
Private/Tiernan's          1
hockingstuart/Barry        1
One                        1
hockingstuart/Jellis       1
Blue                       1
Weast                      1
Oriental                   1
Bustin                     1
Iconek                     1
Marvelli                   1
Rayner                     1
Mason                      1
Joseph                     1
Landfield                  1
hockingstuart/Buxton       1
Joe                        1
WHITEFOX                   1
Vic                        1
Point                      1
North                      1
Luxe                       1
Name: SellerG, dtype: int64
236
3073.0    444
3046.0    354
3020.0    340
3121.0    334
3165.0    314
3058.0    312
3040.0    294
3163.0    285
3032.0    271
3146.0    266
3072.0    263
3181.0    263
3012.0    261
3204.0    257
3101.0    251
3186.0    248
3084.0    247
3141.0    242
3182.0    235
3056.0    228
3187.0    226
3124.0    226
3104.0    224
3145.0    224
3188.0    217
3122.0    216
3127.0    214
3070.0    210
3015.0    209
3011.0    204
         ...
3034.0     88
3067.0     78
3162.0     78
3051.0     76
3167.0     74
3126.0     73
3065.0     73
3066.0     72
3189.0     71
3128.0     71
3018.0     70
3102.0     66
3148.0     64
3054.0     58
3019.0     55
3087.0     49
3053.0     49
3006.0     47
3161.0     44
3052.0     37
3003.0     36
3085.0     34
3002.0     29
3043.0     27
3183.0     26
3021.0     25
3047.0     24
3083.0     16
3061.0     10
3008.0     10
Name: Postcode, dtype: int64
94

In [19]:
data.groupby('Postcode')['Price'].mean().round().astype(int)

Postcode
3000.0     701237
3002.0    1390227
3003.0     958640
3006.0     634458
3008.0     875000
3011.0     773547
3012.0     739548
3013.0     945365
3015.0     979722
3016.0    1194479
3018.0     855139
3019.0     645379
3020.0     625838
3021.0     563024
3025.0     755567
3031.0     797362
3032.0     916211
3033.0     777125
3034.0     832062
3039.0    1116106
3040.0    1058348
3041.0    1067759
3042.0     782726
3043.0     660180
3044.0     744087
3046.0     660247
3047.0     485114
3051.0     846656
3052.0    1364958
3053.0    1049613
           ...
3126.0    2351400
3127.0    1476780
3128.0    1195681
3141.0    1026034
3142.0    1699373
3143.0    1451671
3144.0    1874346
3145.0    1386849
3146.0    1587807
3147.0    1377830
3148.0    1003033
3161.0    1009167
3162.0    1084348
3163.0     909937
3165.0    1056442
3166.0    1052433
3167.0     960679
3181.0    1011799
3182.0     852634
3183.0     714190
3184.0     931183
3185.0    1148307
3186.0    1902363
3187.0    1579980
3188.0    1425744
3189.0     943099
3204.0    1211244
3205.0    1227548
3206.0    1861130
3207.0    1197608
Name: Price, dtype: int32

In [6]:
data.groupby('Postcode')['Price'].apply(lambda x:x.count())

Postcode
3000.0     93
3002.0     22
3003.0     25
3006.0     36
3008.0      5
3011.0    171
3012.0    213
3013.0    139
3015.0    177
3016.0    117
3018.0     66
3019.0     48
3020.0    309
3021.0     21
3025.0     82
3031.0    166
3032.0    233
3033.0    110
3034.0     80
3039.0    129
3040.0    246
3041.0    106
3042.0    168
3043.0     25
3044.0    160
3046.0    301
3047.0     22
3051.0     59
3052.0     33
3053.0     43
         ...
3126.0     45
3127.0    148
3128.0     52
3141.0    187
3142.0    108
3143.0     82
3144.0     68
3145.0    138
3146.0    167
3147.0    122
3148.0     45
3161.0     36
3162.0     56
3163.0    244
3165.0    274
3166.0     82
3167.0     64
3181.0    158
3182.0    192
3183.0     21
3184.0    109
3185.0     70
3186.0    177
3187.0    152
3188.0    166
3189.0     63
3204.0    223
3205.0     73
3206.0     81
3207.0    144
Name: Price, dtype: int64

In [7]:
data.groupby('Postcode')['Price'].apply(lambda x:x.isnull().sum())
# data.groupby('Postcode')['Price'].isnull().sum()

Postcode
3000.0     34
3002.0      7
3003.0     11
3006.0     11
3008.0      5
3011.0     33
3012.0     48
3013.0     36
3015.0     32
3016.0     23
3018.0      4
3019.0      7
3020.0     31
3021.0      4
3025.0     12
3031.0     18
3032.0     38
3033.0     13
3034.0      8
3039.0     23
3040.0     48
3041.0     17
3042.0      7
3043.0      2
3044.0     33
3046.0     53
3047.0      2
3051.0     17
3052.0      4
3053.0      6
         ...
3126.0     28
3127.0     66
3128.0     19
3141.0     55
3142.0     56
3143.0     57
3144.0     75
3145.0     86
3146.0     99
3147.0     50
3148.0     19
3161.0      8
3162.0     22
3163.0     41
3165.0     40
3166.0     23
3167.0     10
3181.0    105
3182.0     43
3183.0      5
3184.0     47
3185.0     26
3186.0     71
3187.0     74
3188.0     51
3189.0      8
3204.0     34
3205.0     19
3206.0     34
3207.0     60
Name: Price, dtype: int64

In [5]:
data['Price']=data['Price'].groupby(data['Postcode']).apply(lambda x :x.fillna(round(x.mean())))

In [6]:
data

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude
0,Abbotsford,68 Studley St,2.0,h,1027385.0,SS,Jellis,3/09/2016,2.5,3067.0,2,1,1,126,NaN,NaN,Yarra,-37.8014,144.9958
1,Abbotsford,85 Turner St,2.0,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,2,1,1,202,NaN,NaN,Yarra,-37.7996,144.9984
2,Abbotsford,25 Bloomburg St,2.0,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,2,1,0,156,79,1900,Yarra,-37.8079,144.9934
3,Abbotsford,18/659 Victoria St,3.0,u,1027385.0,VB,Rounds,4/02/2016,2.5,3067.0,3,2,1,0,NaN,NaN,Yarra,-37.8114,145.0116
4,Abbotsford,5 Charles St,3.0,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,3,2,0,134,150,1900,Yarra,-37.8093,144.9944
5,Abbotsford,40 Federation La,3.0,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,3,2,1,94,NaN,NaN,Yarra,-37.7969,144.9969
6,Abbotsford,55a Park St,4.0,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,3,1,2,120,142,2014,Yarra,-37.8072,144.9941
7,Abbotsford,16 Maugie St,4.0,h,1027385.0,SN,Nelson,6/08/2016,2.5,3067.0,3,2,2,400,220,2006,Yarra,-37.7965,144.9965
8,Abbotsford,53 Turner St,2.0,h,1027385.0,S,Biggin,6/08/2016,2.5,3067.0,4,1,2,201,NaN,1900,Yarra,-37.7995,144.9974
9,Abbotsford,99 Turner St,2.0,h,1027385.0,S,Collins,6/08/2016,2.5,3067.0,3,2,1,202,NaN,1900,Yarra,-37.7996,144.9989
10,Abbotsford,129 Charles St,2.0,h,941000.0,S,Jellis,7/05/2016,2.5,3067.0,2,1,0,181,NaN,NaN,Yarra,-37.8041,144.9953
11,Abbotsford,124 Yarra St,3.0,h,1876000.0,S,Nelson,7/05/2016,2.5,3067.0,4,2,0,245,210,1910,Yarra,-37.8024,144.9993
12,Abbotsford,121/56 Nicholson St,2.0,u,1027385.0,PI,Biggin,7/11/2016,2.5,3067.0,2,2,1,4292,82,2009,Yarra,-37.8078,144.9965
13,Abbotsford,17 Raphael St,4.0,h,1027385.0,W,Biggin,7/11/2016,2.5,3067.0,6,2,0,230,147,1860,Yarra,-37.8066,144.9936
14,Abbotsford,98 Charles St,2.0,h,1636000.0,S,Nelson,8/10/2016,2.5,3067.0,2,1,2,256,107,1890,Yarra,-37.806,144.9954
15,Abbotsford,217 Langridge St,3.0,h,1000000.0,S,Jellis,8/10/2016,2.5,3067.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Abbotsford,18a Mollison St,2.0,t,745000.0,S,Jellis,8/10/2016,2.5,3067.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Abbotsford,6/241 Nicholson St,1.0,u,300000.0,S,Biggin,8/10/2016,2.5,3067.0,1,1,1,0,NaN,NaN,Yarra,-37.8008,144.9973
18,Abbotsford,10 Valiant St,2.0,h,1097000.0,S,Biggin,8/10/2016,2.5,3067.0,3,1,2,220,75,1900,Yarra,-37.801,144.9989
19,Abbotsford,403/609 Victoria St,2.0,u,542000.0,S,Dingle,8/10/2016,2.5,3067.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Abbotsford,2 Rich St,2.0,h,1027385.0,SP,Biggin,10/12/2016,2.5,3067.0,2,1,1,176,80,1925,Yarra,-37.7998,144.9972
21,Abbotsford,25/84 Trenerry Cr,2.0,u,760000.0,SP,Biggin,10/12/2016,2.5,3067.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Abbotsford,106/119 Turner St,1.0,u,481000.0,SP,Purplebricks,10/12/2016,2.5,3067.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,Abbotsford,411/8 Grosvenor St,2.0,u,700000.0,VB,Jellis,12/11/2016,2.5,3067.0,2,2,1,0,NaN,NaN,Yarra,-37.811,145.0067
24,Abbotsford,40 Nicholson St,3.0,h,1350000.0,VB,Nelson,12/11/2016,2.5,3067.0,3,2,2,214,190,2005,Yarra,-37.8085,144.9964
25,Abbotsford,123/56 Nicholson St,2.0,u,750000.0,S,Biggin,12/11/2016,2.5,3067.0,2,2,1,0,94,2009,Yarra,-37.8078,144.9965
26,Abbotsford,22 Park St,4.0,h,1985000.0,S,Biggin,12/11/2016,2.5,3067.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-37.8084,144.9942
27,Abbotsford,13/84 Trenerry Cr,1.0,u,500000.0,S,Biggin,12/11/2016,2.5,3067.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Abbotsford,45 William St,2.0,h,1172500.0,S,Biggin,13/08/2016,2.5,3067.0,2,1,1,195,NaN,NaN,Yarra,-37.8084,144.9973
29,Abbotsford,7/20 Abbotsford St,1.0,u,441000.0,SP,Greg,14/05/2016,2.5,3067.0,1,1,1,0,NaN,NaN,Yarra,-37.8016,144.9988
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14212,Windsor,2/6 The Avenue,2.0,u,690000.0,S,Nelson,13/05/2017,5.1,3181.0,2,1,1,0,Unavailable,Unavailable,Stonnington,-37.85727,144.99782
14213,Windsor,3/217 Dandenong Rd,2.0,u,854000.0,SP,Woodards,22/04/2017,5.1,3181.0,2,1,1,774,90,1945,Stonnington,-37.85821,144.99788
14214,Windsor,108 Peel St,1.0,h,900000.0,VB,hockingstuart,29/04/2017,5.1,3181.0,1,1,1,160,Unavailable,1930,Stonnington,-37.85556,144.98846
14215,Windsor,7/113 Punt Rd,1.0,u,350000.0,SP,Kay,29/04/2017,5.1,3181.0,1,1,0,0,48,1975,Port Phillip,-37.85079,144.98397
14216,Yallambie,24 Bimbadeen Cr,4.0,h,779108.0,PI,Buckingham,8/04/2017,15.0,3085.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14217,Yallambie,19 Goulburn Gr,4.0,h,955000.0,PI,Morrison,13/05/2017,15.0,3085.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14218,Yallambie,57 Tarcoola Dr,3.0,h,721500.0,S,Darren,20/05/2017,15.0,3085.0,3,1,1,594,Unavailable,Unavailable,Banyule,-37.72139,145.10633
14219,Yallambie,14 Borlase St,5.0,h,1060000.0,S,Buckingham,29/04/2017,15.0,3085.0,5,2,2,627,232,1960,Banyule,-37.73271,145.08041
14220,Yallambie,8 Lowan Av,4.0,h,780250.0,SP,hockingstuart,29/04/2017,15.0,3085.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14221,Yallambie,7 Marigolds Rd,3.0,h,984000.0,S,Darren,29/04/2017,15.0,3085.0,3,2,2,552,Unavailable,Unavailable,Banyule,-37.72848,145.08514
14222,Balaclava,4/247 Inkerman St,2.0,u,450000.0,SP,Buxton,13/05/2017,6.6,3183.0,2,1,1,0,50,1960,Port Phillip,-37.8656,144.99188
14223,Balaclava,5/171 Hotham St,2.0,u,490000.0,VB,hockingstuart,29/04/2017,6.6,3183.0,2,1,0,601,Unavailable,Unavailable,Port Phillip,-37.87565,144.99801
14224,Balaclava,2/31 Orange Gr,1.0,u,440000.0,S,hockingstuart,29/04/2017,6.6,3183.0,1,1,0,0,Unavailable,1940,Port Phillip,-37.86858,144.99685
14225,Essendon West,2 Diamond St,3.0,h,1406000.0,S,Nelson,13/05/2017,9.8,3040.0,3,1,1,34,Unavailable,Unavailable,Moonee Valley,-37.75059,144.88914
14226,Essendon West,7 Garnet St,3.0,h,1305000.0,S,Gunn&Co,20/05/2017,9.8,3040.0,3,1,2,147,Unavailable,Unavailable,Moonee Valley,-37.75228,144.88617
14227,Kingsbury,1/37 Clunes St,3.0,u,488000.0,S,Ray,13/05/2017,12.4,3083.0,3,1,1,260,150,1961,Darebin,-37.71569,145.03855
14228,Kooyong,26 Monaro Rd,5.0,h,1874346.0,PI,Marshall,13/05/2017,6.2,3144.0,5,2,4,1784,Unavailable,1920,Stonnington,-37.84306,145.03456
14229,West Melbourne,36 Abbotsford St,2.0,h,958640.0,SN,W.B.,13/05/2017,1.9,3003.0,2,1,0,84,Unavailable,Unavailable,Melbourne,-37.80714,144.94443
14230,West Melbourne,218 Adderley St,3.0,h,1750000.0,S,Woodards,13/05/2017,1.9,3003.0,3,1,1,160,Unavailable,1870,Melbourne,-37.80817,144.94512
14231,West Melbourne,3/212 Roden St,2.0,t,1013000.0,S,Alexkarbon,20/05/2017,1.9,3003.0,2,2,1,0,130,2010,Melbourne,-37.80943,144.94523
14232,West Melbourne,7/234 Roden St,3.0,t,1171000.0,S,Alexkarbon,20/05/2017,1.9,3003.0,3,2,1,650,Unavailable,Unavailable,Melbourne,-37.80978,144.94476
14233,West Melbourne,101/89 Roden St,2.0,u,958640.0,SP,Jellis,20/05/2017,1.9,3003.0,2,2,1,0,Unavailable,Unavailable,Melbourne,-37.80742,144.94867
14234,West Melbourne,105/493 Victoria St,1.0,u,958640.0,PI,Harcourts,20/05/2017,1.9,3003.0,1,1,1,0,51,2007,Melbourne,-37.80473,144.9435
14235,West Melbourne,53 Miller St,2.0,h,1053000.0,S,Purplebricks,22/04/2017,1.9,3003.0,2,1,0,147,Unavailable,1880,Melbourne,-37.80593,144.94592
14236,West Melbourne,316/145 Roden St,1.0,u,295000.0,SP,Alexkarbon,29/04/2017,1.9,3003.0,1,1,1,0,Unavailable,2013,Melbourne,-37.80844,144.94731
14237,Campbellfield,33 Rainsford Tce,3.0,h,445000.0,S,Harcourts,20/05/2017,14.5,3061.0,3,1,2,534,Unavailable,Unavailable,Hume,-37.67413,144.96976
14238,Campbellfield,4 Susan Ct,3.0,h,448286.0,SP,Raine,20/05/2017,14.5,3061.0,3,1,4,534,Unavailable,Unavailable,Hume,-37.67513,144.96944
14239,Caulfield East,3/14 Queens Av,2.0,t,910000.0,SP,Gary,20/05/2017,9.3,3145.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14240,Travancore,456/38 Mt Alexander Rd,2.0,u,360000.0,SP,Pagan,20/05/2017,5.3,3032.0,2,1,1,0,51,2010,Moonee Valley,-37.78466,144.93829
14241,Seaholme,3/1 James Av,2.0,u,855139.0,PI,hockingstuart,22/04/2017,12.7,3018.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [104]:
pd.crosstab(data.Date,data.Rooms)

Rooms       1.0   2.0   3.0   4.0   5.0   99.0
Date
10/09/2016    20   102   136    91    27     6
10/12/2016    32   161   209    94    26     6
11/02/2017    12    54    46    17     2     1
11/03/2017     4    16    23    17     5     0
12/06/2016     4    22    32     8    10     0
12/11/2016    25   143   182    98    22     5
13/05/2017    20   123   170    84    22     3
13/08/2016    14    85    84    40     6     3
14/05/2016    16   116   122    48    16     4
15/10/2016    26   143   187    85    22     3
16/04/2016    12    93   149    59    15     5
16/07/2016    20    69    89    34     5     2
17/09/2016    16   104   166    66    23     2
18/03/2017    31   159   194   101    21     7
18/06/2016    20   121   180    87    30     3
19/11/2016    22   133   163    91    18     4
20/05/2017    19   119   204    88    25     2
22/04/2017    14    81    86    38     4     3
22/05/2016    22    98   126    69    17     4
22/08/2016    21    80   123    57     8     4
23/04/2016     8    51    79    25     6     0
24/09/2016    22   133   153    59     6     4
25/02/2017    31   145   235   120    19     5
26/07/2016     8    65    85    38     1     2
27/06/2016    20   103   148    67    17     2
27/11/2016    31   141   238   135    24     6
28/01/2016     0     1     1     1     0     0
28/05/2016    21   106   194    98    32     3
28/08/2016    24   103   168    74    19     2
29/04/2017    24   106   138    56    16     1
3/09/2016     15    96   138    68    14     2
3/12/2016     32   114   204    98    17     7
30/07/2016    21    87   102    47    11     3
4/02/2016      4    15    19     4     1     1
4/03/2017     26   148   202   115    31    10
4/06/2016     17   108   153    70    13     7
6/05/2017     12    76   103    35     9     1
6/08/2016     13    90    89    47    12     7
7/05/2016     23   114   167    88    22     5
7/11/2016     19   111   120    45    10     1
8/04/2017     38   132   205    65     9     2
8/10/2016     22   130   151    67    14     2

In [8]:
data.loc[data.Rooms > 5,'Rooms']=99

In [9]:
pd.crosstab(data.Rooms,data.Type)

Type      h    t     u
Rooms
1.0      48    7   746
2.0    1479  458  2260
3.0    4428  839   533
4.0    2424  259    24
5.0     619   10     0
99.0     82    1     5

In [10]:
test.Rooms.unique()

NameError: name 'test' is not defined

In [57]:
def room():
    for i in test['Rooms']:
        if i > 3:
            i=99
            return(i)

In [153]:
test.loc[test.Rooms >2,'Rooms']=99
test.loc[test.Landsize=='Unavailable','Landsize']=0
test.loc[test.Landsize==' ','Landsize']=0
test

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,new
0,Abbotsford,68 Studley St,2.0,h,NaN,SS,Jellis,3/09/2016,2.5,3067.0,2,1,1,126,NaN,NaN,Yarra,-37.8014,144.9958,126
1,Abbotsford,85 Turner St,2.0,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,2,1,1,202,NaN,NaN,Yarra,-37.7996,144.9984,202
2,Abbotsford,25 Bloomburg St,2.0,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,2,1,0,156,79,1900,Yarra,-37.8079,144.9934,156
3,Abbotsford,18/659 Victoria St,99.0,u,NaN,VB,Rounds,4/02/2016,2.5,3067.0,3,2,1,0,NaN,NaN,Yarra,-37.8114,145.0116,0
4,Abbotsford,5 Charles St,99.0,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,3,2,0,134,150,1900,Yarra,-37.8093,144.9944,134
5,Abbotsford,40 Federation La,99.0,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,3,2,1,94,NaN,NaN,Yarra,-37.7969,144.9969,94
6,Abbotsford,55a Park St,99.0,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,3,1,2,120,142,2014,Yarra,-37.8072,144.9941,120
7,Abbotsford,16 Maugie St,99.0,h,NaN,SN,Nelson,6/08/2016,2.5,3067.0,3,2,2,400,220,2006,Yarra,-37.7965,144.9965,400
8,Abbotsford,53 Turner St,2.0,h,NaN,S,Biggin,6/08/2016,2.5,3067.0,4,1,2,201,NaN,1900,Yarra,-37.7995,144.9974,201
9,Abbotsford,99 Turner St,2.0,h,NaN,S,Collins,6/08/2016,2.5,3067.0,3,2,1,202,NaN,1900,Yarra,-37.7996,144.9989,202
10,Abbotsford,129 Charles St,2.0,h,941000.0,S,Jellis,7/05/2016,2.5,3067.0,2,1,0,181,NaN,NaN,Yarra,-37.8041,144.9953,181
11,Abbotsford,124 Yarra St,99.0,h,1876000.0,S,Nelson,7/05/2016,2.5,3067.0,4,2,0,245,210,1910,Yarra,-37.8024,144.9993,245
12,Abbotsford,121/56 Nicholson St,2.0,u,NaN,PI,Biggin,7/11/2016,2.5,3067.0,2,2,1,4292,82,2009,Yarra,-37.8078,144.9965,4292
13,Abbotsford,17 Raphael St,99.0,h,NaN,W,Biggin,7/11/2016,2.5,3067.0,6,2,0,230,147,1860,Yarra,-37.8066,144.9936,230
14,Abbotsford,98 Charles St,2.0,h,1636000.0,S,Nelson,8/10/2016,2.5,3067.0,2,1,2,256,107,1890,Yarra,-37.806,144.9954,256
15,Abbotsford,217 Langridge St,99.0,h,1000000.0,S,Jellis,8/10/2016,2.5,3067.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100
16,Abbotsford,18a Mollison St,2.0,t,745000.0,S,Jellis,8/10/2016,2.5,3067.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100
17,Abbotsford,6/241 Nicholson St,1.0,u,300000.0,S,Biggin,8/10/2016,2.5,3067.0,1,1,1,0,NaN,NaN,Yarra,-37.8008,144.9973,0
18,Abbotsford,10 Valiant St,2.0,h,1097000.0,S,Biggin,8/10/2016,2.5,3067.0,3,1,2,220,75,1900,Yarra,-37.801,144.9989,220
19,Abbotsford,403/609 Victoria St,2.0,u,542000.0,S,Dingle,8/10/2016,2.5,3067.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100
20,Abbotsford,2 Rich St,2.0,h,NaN,SP,Biggin,10/12/2016,2.5,3067.0,2,1,1,176,80,1925,Yarra,-37.7998,144.9972,176
21,Abbotsford,25/84 Trenerry Cr,2.0,u,760000.0,SP,Biggin,10/12/2016,2.5,3067.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100
22,Abbotsford,106/119 Turner St,1.0,u,481000.0,SP,Purplebricks,10/12/2016,2.5,3067.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100
23,Abbotsford,411/8 Grosvenor St,2.0,u,700000.0,VB,Jellis,12/11/2016,2.5,3067.0,2,2,1,0,NaN,NaN,Yarra,-37.811,145.0067,0
24,Abbotsford,40 Nicholson St,99.0,h,1350000.0,VB,Nelson,12/11/2016,2.5,3067.0,3,2,2,214,190,2005,Yarra,-37.8085,144.9964,214
25,Abbotsford,123/56 Nicholson St,2.0,u,750000.0,S,Biggin,12/11/2016,2.5,3067.0,2,2,1,0,94,2009,Yarra,-37.8078,144.9965,0
26,Abbotsford,22 Park St,99.0,h,1985000.0,S,Biggin,12/11/2016,2.5,3067.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-37.8084,144.9942,100
27,Abbotsford,13/84 Trenerry Cr,1.0,u,500000.0,S,Biggin,12/11/2016,2.5,3067.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100
28,Abbotsford,45 William St,2.0,h,1172500.0,S,Biggin,13/08/2016,2.5,3067.0,2,1,1,195,NaN,NaN,Yarra,-37.8084,144.9973,195
29,Abbotsford,7/20 Abbotsford St,1.0,u,441000.0,SP,Greg,14/05/2016,2.5,3067.0,1,1,1,0,NaN,NaN,Yarra,-37.8016,144.9988,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,Airport West,23 Hart St,2.0,h,603000.0,S,Nelson,4/03/2017,13.5,3042.0,2,1,1,272,84,1950,Moonee Valley,-37.7294,144.888,272
71,Airport West,1/80 Hawker St,99.0,t,700000.0,S,Brad,4/03/2017,13.5,3042.0,3,2,2,239,134,2009,Moonee Valley,-37.7218,144.8837,239
72,Airport West,1/37 Hillside Gr,99.0,h,600000.0,S,Maddison,4/03/2017,13.5,3042.0,2,1,1,290,116,1980,Moonee Valley,-37.7273,144.8744,290
73,Airport West,2/49 McIntosh St,2.0,u,500000.0,VB,Barry,4/03/2017,13.5,3042.0,2,1,1,168,86,2011,Moonee Valley,-37.7215,144.8864,168
74,Airport West,4/9 West Ct,2.0,t,420000.0,VB,Barry,4/06/2016,13.5,3042.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100
75,Airport West,1/36 York St,99.0,t,500000.0,VB,Nelson,4/06/2016,13.5,3042.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100
76,Airport West,33 Bowes Av,99.0,h,1035000.0,S,Airport,6/08/2016,13.5,3042.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100
77,Airport West,89 Bowes Av,99.0,h,960000.0,S,Barry,6/08/2016,13.5,3042.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100
78,Airport West,45 Laurence Av,99.0,h,960000.0,S,Nelson,6/08/2016,13.5,3042.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100
79,Airport West,54 Marshall Rd,99.0,h,720000.0,S,Barry,6/08/2016,13.5,3042.0,2,1,1,620,NaN,NaN,Moonee Valley,-37.7173,144.8872,620
80,Airport West,36 Roberts Rd,99.0,h,785000.0,S,Considine,6/08/2016,13.5,3042.0,3,1,2,597,127,NaN,Moonee Valley,-37.7259,144.8792,597
81,Airport West,11 Harrington Rd,99.0,h,725000.0,SP,Barry,7/05/2016,13.5,3042.0,6,3,2,976,186,1980,Moonee Valley,-37.7239,144.8735,976
82,Airport West,2/252 Parer Rd,2.0,t,450000.0,S,Barry,7/05/2016,13.5,3042.0,2,1,1,110,90,2015,Moonee Valley,-37.7216,144.871,110
83,Airport West,3/19 Hart St,2.0,u,515000.0,S,Barry,7/11/2016,13.5,3042.0,2,1,1,141,73,2013,Moonee Valley,-37.7298,144.8883,141
84,Airport West,81a Roberts Rd,99.0,h,680000.0,VB,Nelson,8/10/2016,13.5,3042.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100
85,Airport West,2/62 Clydesdale Rd,2.0,u,530000.0,S,Nelson,10/09/2016,13.5,3042.0,2,1,1,120,94,2012,Moonee Valley,-37.7234,144.8792,120
86,Airport West,3 Deidre Ct,99.0,h,895000.0,PI,Rendina,10/09/2016,13.5,3042.0,3,1,6,1063,133,1975,Moonee Valley,-37.7249,144.8728,1063
87,Airport West,3/24 Elstone Av,99.0,u,600000.0,VB,Nelson,10/09/2016,13.5,3042.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100
88,Airport West,13 Etzel St,99.0,h,805000.0,S,Nelson,10/12/2016,13.5,3042.0,3,1,1,0,105,1950,Moonee Valley,-37.7217,144.8783,0
89,Airport West,37a North St,99.0,t,760000.0,PI,Barry,10/12/2016,13.5,3042.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100
90,Airport West,1/43 Cameron St,99.0,u,752000.0,S,Nelson,11/02/2017,13.5,3042.0,3,1,1,265,130,1993,Moonee Valley,-37.7302,144.8855,265
91,Airport West,1/69 Bowes Av,99.0,u,580000.0,VB,Nelson,12/11/2016,13.5,3042.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100
92,Airport West,2/9 El Reno Cr,99.0,h,725000.0,PI,Ray,12/11/2016,13.5,3042.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100
93,Airport West,92 McNamara Av,99.0,h,758000.0,S,Jellis,13/08/2016,13.5,3042.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100
94,Airport West,145a Victory Rd,2.0,u,440000.0,S,Barry,13/08/2016,13.5,3042.0,2,1,1,192,NaN,NaN,Moonee Valley,-37.7177,144.8787,192
95,Airport West,20 Creswell Av,99.0,h,970000.0,S,Barry,14/05/2016,13.5,3042.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100
96,Airport West,241 Parer Rd,99.0,h,755000.0,PI,Propertyau,14/05/2016,13.5,3042.0,3,2,2,596,NaN,NaN,Moonee Valley,-37.7248,144.8699,596
97,Airport West,71 Bowes Av,99.0,h,985000.0,S,Barry,15/10/2016,13.5,3042.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100
98,Airport West,2/40 Earl St,99.0,t,700000.0,PI,Brad,15/10/2016,13.5,3042.0,3,2,2,165,133,2009,Moonee Valley,-37.727,144.887,165
99,Airport West,2/112 Parer Rd,2.0,u,509500.0,SP,Nelson,15/10/2016,13.5,3042.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100

In [11]:
data.Distance.mean()

8.621635494304728

In [222]:
data.Type.unique()

array(['h', 'u', 't'], dtype=object)

In [112]:

import folium
mapit = None
latlon = [ (51.249443914705175, -0.13878830247011467), (51.249443914705175, -0.13878830247011467), (51.249768239976866, -2.8610415615063034)]
for coord in latlon:
    mapit = folium.Map( location=[ coord[0], coord[1] ] )

mapit.save( 'map.html')

In [113]:
data.Price.isnull().sum()

3173

In [114]:
data.BuildingArea.isnull().sum()

7166

In [12]:
data.count()

Suburb          14242
Address         14232
Rooms           14222
Type            14222
Price           14222
Method          14222
SellerG         14222
Date            14222
Distance        14222
Postcode        14222
Bedroom2        11222
Bathroom        11222
Car             11222
Landsize        11213
BuildingArea     7076
YearBuilt        7852
CouncilArea     11213
Lattitude       11307
Longtitude      11307
dtype: int64

In [13]:
data=data[data['Suburb']!='    RE']
data.Suburb.unique()

array(['Abbotsford', 'Airport West', 'Albert Park', 'Alphington', 'Altona',
       'Altona North', 'Armadale', 'Ascot Vale', 'Ashburton', 'Ashwood',
       'Avondale Heights', 'Balaclava', 'Balwyn', 'Balwyn North',
       'Bentleigh', 'Bentleigh East', 'Box Hill', 'Braybrook', 'Brighton',
       'Brighton East', 'Brunswick', 'Brunswick West', 'Bulleen',
       'Burwood', 'Camberwell', 'Canterbury', 'Carlton North', 'Carnegie',
       'Caulfield', 'Caulfield North', 'Caulfield South', 'Chadstone',
       'Clifton Hill', 'Coburg', 'Coburg North', 'Collingwood',
       'Doncaster', 'Eaglemont', 'Elsternwick', 'Elwood', 'Essendon',
       'Essendon North', 'Fairfield', 'Fitzroy', 'Fitzroy North',
       'Flemington', 'Footscray', 'Glen Iris', 'Glenroy', 'Gowanbrae',
       'Hadfield', 'Hampton', 'Hampton East', 'Hawthorn',
       'Heidelberg Heights', 'Heidelberg West', 'Hughesdale', 'Ivanhoe',
       'Kealba', 'Keilor East', 'Kensington', 'Kew', 'Kew East', 'Kooyong',
       'Maidstone', 'Malvern', 'Malvern East', 'Maribyrnong', 'Melbourne',
       'Middle Park', 'Mont Albert', 'Moonee Ponds', 'Moorabbin',
       'Newport', 'Niddrie', 'North Melbourne', 'Northcote', 'Oak Park',
       'Oakleigh South', 'Parkville', 'Pascoe Vale', 'Port Melbourne',
       'Prahran', 'Preston', 'Reservoir', 'Richmond', 'Rosanna', 'Seddon',
       'South Melbourne', 'South Yarra', 'Southbank', 'Spotswood',
       'St Kilda', 'Strathmore', 'Sunshine', 'Sunshine North',
       'Sunshine West', 'Surrey Hills', 'Templestowe Lower', 'Thornbury',
       'Toorak', 'Viewbank', 'Watsonia', 'West Melbourne', 'Williamstown',
       'Williamstown North', 'Windsor', 'Yallambie', 'Yarraville',
       'Aberfeldie', 'Bellfield', 'Brunswick East', 'Burnley',
       'Campbellfield', 'Carlton', 'East Melbourne', 'Essendon West',
       'Fawkner', 'Hawthorn East', 'Heidelberg', 'Ivanhoe East', 'Jacana',
       'Kingsbury', 'Kingsville', 'Murrumbeena', 'Ormond',
       'West Footscray', 'Albion', 'Brooklyn', 'Glen Huntly', 'Oakleigh',
       'Ripponlea', 'Cremorne', 'Docklands', 'South Kingsville',
       'Strathmore Heights', 'Travancore', 'Caulfield East', 'Seaholme',
       'Keilor Park', 'Gardenvale', 'Princes Hill'], dtype=object)

In [14]:
from sklearn.preprocessing import OneHotEncoder,LabelEncoder
label_enc=LabelEncoder()

In [19]:
X=data[['Rooms','Type','Method','Distance','Price']].values

In [20]:
y=data['Postcode'].values

In [21]:
X[:,1] =label_enc.fit_transform(X[:,1])
X[:,2] =label_enc.fit_transform(X[:,2])
onehot_enc=OneHotEncoder(categorical_features=[1,2])
X=onehot_enc.fit_transform(X).toarray()

In [23]:
np.unique(X[:,2])

array([ 0.,  1.])

In [24]:
X

array([[  1.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          2.00000000e+00,   2.50000000e+00,   1.02738500e+06],
       [  1.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          2.00000000e+00,   2.50000000e+00,   1.48000000e+06],
       [  1.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          2.00000000e+00,   2.50000000e+00,   1.03500000e+06],
       ...,
       [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00, ...,
          2.00000000e+00,   9.30000000e+00,   9.10000000e+05],
       [  0.00000000e+00,   0.00000000e+00,   1.00000000e+00, ...,
          2.00000000e+00,   5.30000000e+00,   3.60000000e+05],
       [  0.00000000e+00,   0.00000000e+00,   1.00000000e+00, ...,
          2.00000000e+00,   1.27000000e+01,   8.55139000e+05]])

In [25]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit_transform(["paris", "paris", "tokyo", "amsterdam"])

array([1, 1, 2, 0], dtype=int64)

In [26]:
y[0:]=le.fit_transform(y)

In [27]:
np.unique(y)

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
        11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,
        22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,
        33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,
        44.,  45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,
        55.,  56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,
        66.,  67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,
        77.,  78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,
        88.,  89.,  90.,  91.,  92.,  93.])

In [28]:
y

array([ 39.,  39.,  39., ...,  71.,  16.,  10.])

In [29]:
from sklearn.multioutput import MultiOutputClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.utils import shuffle

In [30]:
X1,y1=X,y

In [31]:
y2=shuffle(y1,random_state=1)
y3=shuffle(y1,random_state=2)

In [32]:
Y=np.vstack((y1,y2,y3)).T
Y

array([[ 39.,  82.,  93.],
       [ 39.,  12.,  67.],
       [ 39.,  15.,  44.],
       ...,
       [ 71.,  73.,  16.],
       [ 16.,  10.,  63.],
       [ 10.,  41.,  41.]])